apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dna-admin
  namespace: default
  annotations:
    class: public
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # If you're using cert-manager for SSL
  labels:
    app: dna-admin
spec:
  rules:
    - host: dna-admin.instinct.is
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dna-entrypoint
                port:
                  number: 8080
  tls:
    - hosts:
        - dna-admin.instinct.is
          # secretName: dna-tls  # This is the secret that will store the SSL certificate
