development: &DEFAULTS
  bucket: <%= ENV['AWS_BUCKET_NAME'] %>
  s3_region: <%= ENV['AWS_REGION_NAME'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

test:
  <<: *DEFAULTS
  bucket: <%= ENV['AWS_BUCKET_NAME'] %>

production:
  <<: *DEFAULTS
  bucket: <%= ENV['AWS_BUCKET_NAME'] %>
